import Head from 'next/head'
import AdminLayout from '@/layouts/AdminLayout'
import AdminForAnswer from '@/components/Admin/SuperAdmin/Answer'

export default function AdminForAnswerPage() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AdminLayout>
                <AdminForAnswer />
            </AdminLayout>
        </>
    )
}
