
import Register from '@/components/Share/Login/Register';
import AuthLayout from '@/layouts/AuthLayout';
import Head from 'next/head';

const RegisterPage = () => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AuthLayout>
                <Register />
            </AuthLayout>
        </>
    )
}

export default RegisterPage;