import ManageTest from '@/components/Admin/Test/Manage'
import StudentTest from '@/components/Client/StudentTask/Test'
import ClientLayout from '@/layouts/ClientLayout'
import Head from 'next/head'
import React from 'react'

const StudentTestingPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ClientLayout>
                <StudentTest />
            </ClientLayout>
        </>
    )
}

export default StudentTestingPage